version: '3.8'
volumes:
  config:
networks:
  devproxy:
    name: devproxy
services:
  devproxy:
    build: docker/
    init: true
    restart: unless-stopped
    volumes:
      - config:/config
      - ./docker/entrypoint.sh:/entrypoint.sh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devproxy
