version: '3.4'
networks:
  devproxy:
    external:
      name: devproxy
services:
  devproxy:
    build: docker/
    ports:
      - "443:443"
      - "4430:4430"
    volumes:
      - ./config:/config
      - ./docker/entrypoint.sh:/entrypoint.sh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devproxy
