api:
  insecure: true
  dashboard: true
providers:
  docker:
    exposedByDefault: false
    endpoint: tpc://dockerproxy:2375
    network: devproxy2
    defaultRule: "Host(`{{ index .Labels \"devDomain\"}}.test`)"
http:

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          permanent: false
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: stepca
certificatesResolvers:
  stepca:
    acme:
      storage: /traefik-certs/acme.json
      email: dummy
      caServer: https://step-ca/acme/dev/directory
      dnsChallenge:
        provider: httpreq
        delayBeforeCheck: 0
        disablepropagationcheck: true
log: true
        # - "--providers.file.filename=/dynamic-conf.yml"
        #- "--providers.file.watch=true"
        #- "--accesslog=false"
        #- "--log=true"
        # - "--log.level=DEBUG"

